//Repeat a string 3 times.

// Algorithms
// Step 1. Take a string and hold it in a variable
// Step 2. Define a function that takes a string as an argument
// Step 3. Assign the string value to a variable
// Step 4. Use Javascript method to repeat string 3 times
// Step 5. Print or return the value

// Pseudo Code
// function repeatStringThreeTimes(string)
// repeatThreeTimes = string.repeat(3)
// print repeatThreeTimes

// Source code
const myCompanyName = "Soft-D-Go";
function repeatStringThreeTimes(company) {
  const repeatThreeTimes = company.repeat(3);
  return repeatThreeTimes();
}
console.log(repeatStringThreeTimes(myCompanyName));
